inherit_gem:
  bixby: bixby_default.yml

Metrics/BlockLength:
  Exclude:
    - 'config/**/*'
    - 'app/controllers/catalog_controller.rb'
    - 'spec/**/*'
    - 'app/models/concerns/tufts/**/*'
Metrics/LineLength:
   Exclude:
    - 'spec/controllers/tufts/draft_controller_spec.rb'
Metrics/MethodLength:
   Exclude:
    - 'app/models/forms/contribution.rb'
RSpec/ExampleLength:
   Exclude:
    - 'spec/features/**/*'
    - 'spec/controllers/tufts/draft_controller_spec.rb'
    - 'spec/lib/import_export/deposit_type_importer_spec.rb'
    - 'spec/lib/import_export/deposit_type_exporter_spec.rb'
    - 'spec/lib/deposit_types_controller_spec.rb'
    - 'spec/lib/tufts/workflow_setup_spec.rb'
    - 'spec/controllers/contribute_controller_spec.rb'
    - 'spec/controllers/deposit_types_controller_spec.rb'
RSpec/NestedGroups:
  Exclude:
   - 'spec/controllers/deposit_types_controller_spec.rb'
   - 'spec/controllers/contribute_controller_spec.rb'
RSpec/AnyInstance:
  Exclude:
   - 'spec/controllers/deposit_types_controller_spec.rb'
   - 'spec/lib/deposit_types_controller_spec.rb'
RSpec/MultipleExpectations:
  Exclude:
  - 'spec/controllers/contribute_controller_spec.rb'
  - 'spec/features/**/*'
  - 'spec/lib/tufts/workflow_setup_spec.rb'
Style/FileName:
  Exclude:
    - '**/Capfile'
    - '**/Gemfile'
    - '**/*.rake'
    - 'config/deploy/*'
