# Generated by hyrax:models
class Collection < ActiveFedora::Base
  include ::Hyrax::CollectionBehavior

  # Do not define any properties after OrderedFields
  # is included.  See ordered_fields.rb for more info.
  include ::Tufts::Metadata::OrderedFields

  self.indexer = Hyrax::CollectionWithBasicMetadataIndexer
end
