class PidUtils
  NAMESPACE_DRAFT = 'draft'.freeze
  NAMESPACE_PUBLISHED = 'tufts'.freeze

  def self.draft_namespace
    NAMESPACE_DRAFT
  end

  def self.published_namespace
    NAMESPACE_PUBLISHED
  end

  def self.draft?(pid)
    pid && pid.start_with?(draft_namespace)
  end

  def self.published?(pid)
    pid && pid.start_with?(published_namespace)
  end

  def self.to_draft(pid)
    "#{draft_namespace}:#{stripped_pid(pid)}"
  end

  def self.to_published(pid)
    "#{published_namespace}:#{stripped_pid(pid)}"
  end

  def self.stripped_pid(pid)
    pid.sub(/.+:(.+)$/, '\1')
  end

  def self.autogenerated?(pid)
    /^[^:]+:\d+$/.match(pid)
  end
end
